name: Trigger Commit V1

on:
  workflow_dispatch:
    inputs:
      email:
        description: "Email for commit step"
        required: true
        type: string

jobs:
  test:
    steps:
      - name: 22f3002165@ds.study.iitm.ac.in
        run: echo "Hello, world!"
